### ISSUE TITLE
Unconditionally cloning a reference to store it is an anti-pattern

### ISSUE THREAD

**Issue by tov** [mmgeorge/rust-odata#3]
[This](https://mmgeorge.github.io/rust-odata/rust_odata/service/struct.ServiceBuilder.html#method.new), for example:

That is, this

```
impl ServiceBuilder {
    pub fn new(name: &str) -> ServiceBuilder
    {
        ServiceBuilder {
            name: String::from(name),
            models: HashMap::new()
        }
    }
```

should probably take a `String` instead. The reason is that if the caller has a `String` it no longer wants, taking it by move avoid an allocation. But if the caller has a `&str` or a `String` it wants to keep, you allocate either way.

The exception would be if the method is always called with a string literal. Which this may very well be.

**Comment by mmgeorge** [comment]
I think the arg would always be a string literal -- the user would here naming the service. I.e.

ServiceBuilder::new("myservicename")

Assuming this is the case, does this involve any extra allocation? Does the compiler just move the string?

**Comment by tov** [comment]
In this case, it involves one allocation, which is the minimum to get a String in any case, so no extra.
